name: Pull Request
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-with-trunk:
    name: Build with trunk
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

        # This uses the rust-toolchain.toml file to make sure we have the targets/toolchains we need
      - name: Ensure rust toolchain is what we need
        run: rustup show

      - name: Cache rust stuff
        uses: Swatinem/rust-cache@v2

      - name: Install trunk
        uses: taiki-e/install-action@v2
        with:
          tool: trunk

      - name: Build
        run: |
          trunk build
        working-directory: .
  test:
    name: Run tests with nextest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

        # This uses the rust-toolchain.toml file to make sure we have the targets/toolchains we need
      - name: Ensure rust toolchain is what we need
        run: rustup show

      - name: Install nextest
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-nextest

      - name: Run nextest
        run: cargo nextest run
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

        # This uses the rust-toolchain.toml file to make sure we have the targets/toolchains we need
      - name: Ensure rust toolchain is what we need
        run: rustup show

      - name: Run clippy
        run: cargo clippy --all-targets -- --deny warnings
  format:
    name: Check format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install nightly and cargo fmt
        run:
          rustup install nightly --profile minimal &&
          rustup component add rustfmt --toolchain nightly

      - name: Run cargo fmt
        run: cargo +nightly fmt --all --check
