name: Pull Request
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-with-bun:
    name: Build with bun
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install bun
        uses: oven-sh/setup-bun@v2

      - name: Install deps
        run: bun install

      - name: Build
        run: bun run build
        working-directory: .
  test:
    name: Run tests with bun
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install bun
        uses: oven-sh/setup-bun@v2

      - name: Install deps
        run: bun install

      - name: Test with bun
        run: bun test
  biome:
    name: Lint and check format with Biome
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install bun
        uses: oven-sh/setup-bun@v2

      - name: Check format/lint with biome
        run: bunx biome ci