name: Pull Request
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v3

     - name: Ensure rust toolchain is what we need
       run: rustup show

     - name: Cache rust stuff
       uses: Swatinem/rust-cache@v2

     - name: Install trunk
       uses: jetli/trunk-action@v0.4.0
       with:
         version: 'latest'

     - name: Build
       run: |
         trunk build
       working-directory: web-frontend
